version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_API_URL=http://backend:3001
    networks:
      - bitcoin-explorer-network

networks:
  bitcoin-explorer-network:
    external: true

